name: Docker Image CI (aws)

on:
  push:
    branches: [ main ]
    paths:
      - 'aws-php/**'
  workflow_dispatch:

jobs:

  build-aws-php74:
    runs-on: ubuntu-latest

    steps:
      # 現在日取得
      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      # ソースを取得
      - name: checkout
        uses: actions/checkout@v3

      # docker環境準備
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # dockerhubログイン
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
#          password: ${{ secrets.CF_PAT }}

      # docker build実施
      - name: Build and push (aws-php74)
        uses: docker/build-push-action@v3
        with:
          context: aws-php/aws-php74/.
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/aws-php74:latest
            ghcr.io/${{ github.repository_owner }}/aws-php74:${{ steps.date.outputs.date }}

  build-aws-php80:
    runs-on: ubuntu-latest

    steps:
      # 現在日取得
      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      # ソースを取得
      - name: checkout
        uses: actions/checkout@v3

      # docker環境準備
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # dockerhubログイン
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
#          password: ${{ secrets.CF_PAT }}

      # docker build実施
      - name: Build and push (aws-php80)
        uses: docker/build-push-action@v3
        with:
          context: aws-php/aws-php80/.
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/aws-php80:latest
            ghcr.io/${{ github.repository_owner }}/aws-php80:${{ steps.date.outputs.date }}

#    - name: Build the Docker image
#      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
