name: Docker Image CI

on:
  push:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: dev-
      DT: 

    steps:
      # ソースを取得
      - name: checkout
        uses: actions/checkout@v2

      # docker環境準備
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # dockerhubログイン
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
#          password: ${{ secrets.CF_PAT }}

      # docker build実施
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: aws-php/aws-php74/.
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}aws-php74:latest
            ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}aws-php74:${{ $(date +%s) }}

#    - name: Build the Docker image
#      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
