name: Docker Image CI (centos7)

on:
  push:
    branches: [ main ]
    paths:
      - 'centos/c7**'
      - 'centos-php/centos7**'

  workflow_dispatch:

jobs:

  build-centos7-systemd:
    runs-on: ubuntu-latest

    steps:
      # 現在日取得
      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      # ソースを取得
      - name: checkout
        uses: actions/checkout@v3

      # docker環境準備
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # dockerhubログイン
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # docker build実施
      - name: Build and push (centos7-systemd)
        uses: docker/build-push-action@v3
        with:
          context: centos/c7_systemd/.
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/centos7-systemd:latest
            ghcr.io/${{ github.repository_owner }}/centos7-systemd:${{ steps.date.outputs.date }}

  build-centos7-php56:
    runs-on: ubuntu-latest
    needs: build-centos7-systemd

    steps:
      # 現在日取得
      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      # ソースを取得
      - name: checkout
        uses: actions/checkout@v3

      # docker環境準備
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # dockerhubログイン
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # docker build実施
      - name: Build and push (centos7-php56)
        uses: docker/build-push-action@v3
        with:
          context: centos-php/centos7-php56/.
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/centos7-php56:latest
            ghcr.io/${{ github.repository_owner }}/centos7-php56:${{ steps.date.outputs.date }}

  build-centos7-php74:
    runs-on: ubuntu-latest
    needs: build-centos7-systemd

    steps:
      # 現在日取得
      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      # ソースを取得
      - name: checkout
        uses: actions/checkout@v3

      # docker環境準備
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # dockerhubログイン
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # docker build実施
      - name: Build and push (centos7-php74)
        uses: docker/build-push-action@v3
        with:
          context: centos-php/centos7-php74/.
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/centos7-php74:latest
            ghcr.io/${{ github.repository_owner }}/centos7-php74:${{ steps.date.outputs.date }}

#    - name: Build the Docker image
#      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
