name: Docker Image CI (centos7)

on:
  push:
    branches: [ main ]
    paths:
      - 'centos/c7**'

jobs:

  build-centos7-systemd:
    runs-on: ubuntu-latest

    steps:
      # 現在日取得
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      # ソースを取得
      - name: checkout
        uses: actions/checkout@v2

      # docker環境準備
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # dockerhubログイン
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
#          password: ${{ secrets.CF_PAT }}

      # docker build実施
      - name: Build and push (centos7-systemd)
        uses: docker/build-push-action@v2
        with:
          context: centos/c7_systemd/.
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/centos7-systemd:latest
            ghcr.io/${{ github.repository_owner }}/centos7-systemd:${{ steps.date.outputs.date }}

#    - name: Build the Docker image
#      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
