name: Docker Image CI (centos5)

on:
  push:
    branches: [ main ]
    paths:
      - 'centos/c5**'
  workflow_dispatch:

jobs:

  build-c5-vault:
    runs-on: ubuntu-latest

    steps:
      # 現在日取得
      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      # ソースを取得
      - name: checkout
        uses: actions/checkout@v3

      # docker環境準備
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # dockerhubログイン
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # docker build実施
      - name: Build and push (centos5-vault)
        uses: docker/build-push-action@v3
        with:
          context: centos/c5_vault/.
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/centos5-vault:latest
            ghcr.io/${{ github.repository_owner }}/centos5-vault:${{ steps.date.outputs.date }}
